name: Branch PR Policy Check

on:
  pull_request_target:
    branches: [main]

jobs:
  check_and_close_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check PR source branch
        id: check_branch
        run: |
          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "close_pr=true" >> $GITHUB_OUTPUT
          else
            echo "close_pr=false" >> $GITHUB_OUTPUT
          fi

      - name: Close PR if not from staging
        if: steps.check_branch.outputs.close_pr == 'true'
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "We only accept pull requests from the staging branch to main. This PR will be closed automatically."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}