name: Check Grafana Port

on:
    schedule:
        - cron: '*/15 * * * *'
    workflow_dispatch:

jobs:
    check-grafana:
        runs-on: ubuntu-latest

        steps:
            - name: Check Grafana Port Accessibility
              uses: nrukavkov/open-ports-check-action@v1
              id: check_port
              with:
                port: 3000
                host: '${{ secrets.GRAFANA_IP }}'
                pause: 1000
                needFail: 'true'
                reverse: 'false'
            
            - name: Get Formatted Date
              id: date
              run: |
                echo "date=$(TZ='America/Chicago' date +'%m-%d-%y %I:%M %p %Z')" >> $GITHUB_OUTPUT
            
            - name: Create Issue If The Port Is Not Accessible
              if: steps.check_port.outcome == 'failure'
              uses: dacbd/create-issue-action@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                title: "🚨 Garfana Port Inaccessible"
                labels: garfana,infrastructure,port-inaccessible
                body: |
                    Garfana port inaccessible detected at ${{ steps.date.outputs.date }}

                    The Garfana port 3000 is not accessible. Please check Security Groups, instance status, etc.

                    [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
