name: Infracost

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  # This stage runs the Infracost CLI and posts PR comments.
  # It also updates PR comments when the PR is updated (synchronize event).
  infracost-pull-request-checks:
    name: Infracost Pull Request Checks
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required to post comments
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=. \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v4

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=./terraform \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json 
                          
      - name: Generate Infracost breakdown
        run: |
          infracost breakdown --path=./terraform \
                              --format=json \
                              --out-file=/tmp/infracost-breakdown.json \
                              --show-skipped

      # Posts a comment to the PR using the 'update' behavior.
      # This creates a single comment and updates it. The "quietest" option.
      # The other valid behaviors are:
      #   delete-and-new - Delete previous comments and create a new one.
      #   hide-and-new - Minimize previous comments and create a new one.
      #   new - Create a new cost estimate comment on every push.
      # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
      - name: Post Infracost Breakdown comment
        run: |
          infracost comment github --path=/tmp/infracost-breakdown.json \
                                  --repo=$GITHUB_REPOSITORY \
                                  --github-token=${{ github.token }} \
                                  --pull-request=${{ github.event.pull_request.number }} \
                                  --behavior=update \
                                  --format=custom-markdown \
      - name: Post Infracost Breakdown comment
        run: |
          infracost comment github --path=/tmp/infracost-base.json \
                                  --repo=$GITHUB_REPOSITORY \
                                  --github-token=${{ github.token }} \
                                  --pull-request=${{ github.event.pull_request.number }} \
                                  --behavior=update \
                                  --format=custom-markdown \

