name: 'Terraform Apply'

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Apply Flow'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    env:
      TF_VAR_BACKEND_BUCKET: ${{ vars.BUCKET_NAME }}
      TF_VAR_BACKEND_KEY: ${{ vars.STATE_KEY }}
      TF_VAR_BACKEND_REGION: ${{ vars.REGION }}
      TF_VAR_BACKEND_DYNAMODB_TABLE: ${{ vars.DYNAMODB_NAME }}
    
    steps:
      # Configure AWS Creds
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.REGION }}
        
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
      
      # Install latest version of terraform CLI
      - name: Setup Terraform
        uses: hasicorp/setup-terraform@v3
      
      # run terraform init
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${TF_VAR_BACKEND_BUCKET}" \
            -backend-config="key=${TF_VAR_BACKEND_KEY}" \
            -backend-config="region=${TF_VAR_BACKEND_REGION}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${TF_VAR_BACKEND_DYNAMODB_TABLE}"
      
      # while this was ran in the PR checks, going to add it here for a record of it in the apply as well
      - name: Terraform Plan
        run: terraform plan -input=false
      
      # Run Terraform Apply
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve