name: 'Drift Detection'

on:
    schedule:
        # runs this every hour
        - cron: '0 * * * *'
    workflow_dispatch: # temporary

jobs:
    detect_drift:
        uses: ./.github/workflows/tfplan.yml
        permissions:
            contents: read
            id-token: write
            pull-requests: write
        secrets:
            ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
    
    notify_on_failure:
        needs: detect_drift
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Create Issue on Drif Detection
              uses: actions/github-script@v7
              with:
                script: |
                    await github.rest.issues.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: '🚨 Infrastructure Drift Detected',
                        body: `Infrastructure drift was detected during the automated hourly check.
                              
                              Please investigate the changes in the AWS environment.
                              
                              [View Workflow Run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
                    });
