name: 'Drift Detection'

on:
    schedule:
        # runs this every hour
        - cron: '0 * * * *'

permissions:
    contents: read
    id-token: write
    pull-requests: write
    issues: write
    actions: read    # Add this permission
    checks: write   # Add this permission

jobs:
    # this one checks for instance types
    detect_drift:
        uses: ./.github/workflows/tfplan.yml 
        permissions:
            contents: read
            id-token: write
            pull-requests: write
            issues: write
        secrets:
            ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
            EXPECTED_ACCOUNT_ID: ${{ secrets.EXPECTED_ACCOUNT_ID }}
    
    analyze_drift:
      needs: detect_drift
      permissions:
        contents: read
        issues: write
      runs-on: ubuntu-latest
      steps:
        - name: Download Terraform Plan
          uses: actions/download-artifact@v4
          with:
            name: terraform-plan
            path: /tmp
        
        - name: Analyze Plan
          id: analyze
          run: |
            PLAN_OUTPUT=$(cat /tmp/plan.json)

            if echo "$PLAN_OUTPUT" | grep -q '"resource_drift":'; then
              echo "DRIFT_DETECTED=true" >> $GITHUB_ENV

              DRIFT_DETAILS=$(echo "$PLAN_OUTPUT" | jq -r '.resource_drift[] | "- Resource: \(.address)\n  Action: \(.change.actions[0])\n  Details: Changed from \(.change.before.tags_all.Name) to \(.change.after.tags_all.Name)"')
              echo "DRIFT_DETAILS<<EOF" >> $GITHUB_ENV
              echo "$DRIFT_DETAILS" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            else
              echo "DRIFT_DETECTED=false" >> $GITHUB_ENV
            fi
        
        - name: Get Formatted Date
          id: date
          run: |
            echo "date=$(TZ='America/Chicago' date +'%m-%d-%y %I:%M %p %Z')" >> $GITHUB_OUTPUT
        
        - name: Create Issue
          if: env.DRIFT_DETECTED == 'true'
          uses: dacbd/create-issue-action@main
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "🚨 Infrastructure Drift Detected"
            labels: drift-detected,infrastructure
            body: |
              Infrastructure drift detected at ${{ steps.date.outputs.date }}
              
              The following resources have drifted from their Terraform-managed state:
              
              ${{ env.DRIFT_DETAILS }}
              

              [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})