name: 'Drift Detection'

on:
    schedule:
        # runs this every hour
        - cron: '0 * * * *'
    workflow_dispatch: # temporary

jobs:
    # this one checks for instance types
    detect_drift:
        uses: ./.github/workflows/tfplan.yml 
        permissions:
            contents: read
            id-token: write
            pull-requests: write
        secrets:
            ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
    
    # This will check to see if the instance has been
    # deleted from AWS not through Terraform
    # and creates an issue.
    check_instance_exists:
        needs: detect_drift
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: Download plan artifact
              uses: actions/download-artifact@v4
              with:
                name: terraform-plan
                path: /tmp
            
            - name: Setup OPA
              uses: open-policy-agent/setup-opa@v2
              with:
                version: latest
            
            - name: Check for drift
              run: |
                opaout=$(opa eval --data ./policies/drift-policy.rego --input /tmp/plan.json "data.terraform.deny" | jq -r '.result[]?.expressions[]?.value[]? // empty')
                if [ ! -z "$opaout" ]; then
                  echo "::error::$opaout"
                  exit 1
                fi
            
            - name: Create Issue on Drift Detection
              if: failure()
              uses: actions/github-script@v7
              with:
                script: |
                    await github.rest.issues.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: '🚨 Infrastructure Drift Detected',
                        body: `Infrastructure drift was detected during the automated hourly check.
                            
                            An EC2 instance has been deleted outside of Terraform.
                            
                            [View Workflow Run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
                    });
    