name: Lint

on:
  pull_request:
    branches:
      - staging
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Create TFLint config
        run: |
          cat << EOF > .tflint.hcl
          plugin "aws" {
            enabled = true
            version = "0.27.0"
            source  = "github.com/terraform-linters/tflint-ruleset-aws"
          }

          config {
            call_module_type = "all"
            force = false
          }
          EOF

      - name: Run TFLint
        id: tflint-run
        run: |
          tflint --init
          OUTPUT=$(tflint --format compact 2>&1) || true
          echo "TFLINT_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post TFLint Comment
        uses: GetTerminus/terraform-pr-commenter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commenter_type: tflint
          commenter_input: ${{ env.TFLINT_OUTPUT }}
          commenter_exitcode: ${{ steps.tflint-run.outcome == 'success' && '0' || '1' }}



    
    
    
    # Below was the initial code just for the check, but now
    # we are using a github action that uses TFLint and creates a comment on the PR
    # - uses: terraform-linters/setup-tflint@v4
    #   name: Setup TFLint
    #   with:
    #     tflint_version: v0.52.0

    # - name: Show version
    #   run: tflint --version

    # - name: Init TFLint
    #   run: tflint --init
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}

    # - name: Run TFLint
    #   run: tflint -f compact
    